"""
AetherSAR Phase 5 - mission and search-path routes.

Search paths are generated by the EXISTING Phase 4 planner
(planner.search_planner.generate_lawnmower) over the EXISTING
SearchArea.from_dict() abstraction - no reimplementation here.
"""

from datetime import datetime, timezone
from typing import List, Optional
from uuid import uuid4

from fastapi import APIRouter, Body, HTTPException

from backend.schemas import Mission, MissionCreate, SearchPath, SearchPathRequest
from backend.store import store
from backend.websocket import manager
from planner.search_area import SearchArea
from planner.search_planner import generate_lawnmower

router = APIRouter(prefix="/missions", tags=["missions"])

DEFAULT_SPACING_M = 85.0


def _now_utc_z() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _mission_or_404(mission_id: str) -> dict:
    mission = store.get_mission(mission_id)
    if mission is None:
        raise HTTPException(status_code=404, detail=f"mission not found: {mission_id}")
    return mission


@router.post("", response_model=Mission, status_code=201)
async def create_mission(payload: MissionCreate) -> dict:
    try:
        area = SearchArea.from_dict(payload.search_area.model_dump())
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    mission = {
        "mission_id": uuid4().hex,
        "name": payload.name,
        "status": "created",
        "search_area": area.to_dict(),
        "created_at": _now_utc_z(),
    }
    store.add_mission(mission)
    await manager.broadcast(
        mission["mission_id"],
        {"type": "mission", "mission_id": mission["mission_id"], "data": {"status": mission["status"]}},
    )
    return mission


@router.get("/{mission_id}", response_model=Mission)
def get_mission(mission_id: str) -> dict:
    return _mission_or_404(mission_id)


@router.post("/{mission_id}/search-path", response_model=SearchPath)
async def generate_search_path(
    mission_id: str,
    payload: Optional[SearchPathRequest] = Body(default=None),
) -> dict:
    mission = _mission_or_404(mission_id)
    spacing_m = payload.spacing_m if payload is not None else DEFAULT_SPACING_M
    try:
        area = SearchArea.from_dict(mission["search_area"])
        waypoints = generate_lawnmower(area, spacing_m)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    path = {
        "mission_id": mission_id,
        "spacing_m": spacing_m,
        "waypoints": waypoints,
        "generated_at": _now_utc_z(),
    }
    store.set_search_path(mission_id, path)
    await manager.broadcast(
        mission_id,
        {
            "type": "search_path",
            "mission_id": mission_id,
            "data": {"spacing_m": spacing_m, "waypoint_count": len(waypoints)},
        },
    )
    return path


@router.get("/{mission_id}/search-path", response_model=SearchPath)
def get_search_path(mission_id: str) -> dict:
    _mission_or_404(mission_id)
    path = store.get_search_path(mission_id)
    if path is None:
        raise HTTPException(
            status_code=404,
            detail="search path not generated yet; POST /missions/{mission_id}/search-path first",
        )
    return path


@router.get("/{mission_id}/telemetry")
def get_mission_telemetry(mission_id: str) -> List[dict]:
    """Return the stored telemetry for a mission (empty list if none)."""
    _mission_or_404(mission_id)
    return store.get_telemetry(mission_id)


@router.get("/{mission_id}/detections")
def get_mission_detections(mission_id: str) -> List[dict]:
    """Return the stored detection events for a mission (empty list if none)."""
    _mission_or_404(mission_id)
    return store.get_detections(mission_id)